language: android 
jdk: oraclejdk7 
sudo: required 

env: 
global: 
- MALLOC_ARENA_MAX=2 

android: 
components: 
- build-tools-23.0.1 
- extra-android-support 
- extra-google-google_play_services 
- extra-google-m2repository 
- extra-android-m2repository 
- android-23 

script: 
- ./gradlew :app:lint 
- ./gradlew clean build